server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/zixishi?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jackson:
    time-zone: Asia/Shanghai
  sql:
    init:
      mode: always
      encoding: UTF-8

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.smartstudy.studyroom.mapper: debug
